empty commit
Open-Avenues-Foundation/P21045-2 pull request #2
Opened 2021-12-16 00:50 UTC by IkmosaO

2021-12-23 01:16 UTC, IkmosaO commented
Please check out my index.js, added a few things to file. What do you guys think?
@grimmi5894 @catb0591 @JesusOrozco978 @IgnacioOAF

2022-01-06 01:21 UTC, IgnacioOAF approved these changes
Great job here

2022-01-06 01:21 UTC, IgnacioOAF commented on controller/index.js
> +}
Nit: here you need to add an empty line.

2022-01-06 01:23 UTC, catb0591 reviewed
Going to look at this!

2022-01-06 01:28 UTC, IgnacioOAF requested changes
change this

2022-01-06 01:29 UTC, IgnacioOAF approved these changes

2022-01-08 02:15 UTC, catb0591 approved these changes
This looks great @IkmosaO 
Let me know when this is merged so I can pull this up and start tackling some of the controllers :)

2022-01-08 02:16 UTC, catb0591 commented
@IgnacioOAF - are we okay to merge this when @IkmosaO adds the space at the end?

2022-01-08 11:32 UTC, Ignacio01 commented
Yes, this should be safe to merge.

2022-01-08 15:14 UTC, IkmosaO commented
Alright i added that space, fixed a spelling error in the controllers/index.js  on line 27, and did some formatting.

I'll be merging this branch to main now.

2022-01-08 15:16 UTC, merged